// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include "stdio.h"
#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_hour, 120);
    lv_obj_set_height(ui_hour, 82);
    lv_obj_set_x(ui_hour, -69);
    lv_obj_set_y(ui_hour, -6);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "--");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &ui_font_misansmedi82, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_hour, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_min, 120);
    lv_obj_set_height(ui_min, 82);
    lv_obj_set_x(ui_min, 69);
    lv_obj_set_y(ui_min, -6);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min, "--");
    lv_obj_set_style_text_color(ui_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_min, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_min, &ui_font_misansmedi82, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_min, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_temp);
    lv_obj_set_width(ui_temp, 75);
    lv_obj_set_height(ui_temp, 36);
    lv_obj_set_x(ui_temp, -101);
    lv_obj_set_y(ui_temp, 55);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLable = lv_label_create(ui_temp);
    lv_obj_set_width(ui_tempLable, 74);
    lv_obj_set_height(ui_tempLable, 28);
    lv_obj_set_x(ui_tempLable, 2);
    lv_obj_set_y(ui_tempLable, 2);
    lv_obj_set_align(ui_tempLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLable, "--""\xc2\xb0""C");
    lv_obj_set_style_text_align(ui_tempLable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLable, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_humi);
    lv_obj_set_width(ui_humi, 78);
    lv_obj_set_height(ui_humi, 35);
    lv_obj_set_x(ui_humi, -19);
    lv_obj_set_y(ui_humi, 57);
    lv_obj_set_align(ui_humi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiImage = lv_img_create(ui_humi);
    lv_img_set_src(ui_humiImage, &ui_img_png_humidity24_png);
    lv_obj_set_width(ui_humiImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiImage, -24);
    lv_obj_set_y(ui_humiImage, 0);
    lv_obj_set_align(ui_humiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humiImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiLabel = lv_label_create(ui_humi);
    lv_obj_set_width(ui_humiLabel, 33);
    lv_obj_set_height(ui_humiLabel, 25);
    lv_obj_set_x(ui_humiLabel, 7);
    lv_obj_set_y(ui_humiLabel, -2);
    lv_obj_set_align(ui_humiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humiLabel, "--");
    lv_obj_set_style_text_align(ui_humiLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humiLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dataLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_dataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataLabel, 88);
    lv_obj_set_y(ui_dataLabel, 58);
    lv_obj_set_align(ui_dataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataLabel, "-----");

    ui_statusBar = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_statusBar);
    lv_obj_set_width(ui_statusBar, 286);
    lv_obj_set_height(ui_statusBar, 22);
    lv_obj_set_x(ui_statusBar, 0);
    lv_obj_set_y(ui_statusBar, -62);
    lv_obj_set_align(ui_statusBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_statusBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_statusBar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statusBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi = lv_img_create(ui_statusBar);
    lv_img_set_src(ui_wifi, &ui_img_png_wifi_png);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi, 72);
    lv_obj_set_y(ui_wifi, -63);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batBar = lv_bar_create(ui_statusBar);
    lv_obj_remove_style_all(ui_batBar);
    lv_bar_set_value(ui_batBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batBar, 31);
    lv_obj_set_height(ui_batBar, 24);
    lv_obj_set_align(ui_batBar, LV_ALIGN_RIGHT_MID);
    // lv_obj_set_style_outline_width(ui_batBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_outline_opa(ui_batBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_outline_color(ui_batBar, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_batBar, &ui_img_png_battery0_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_batBar, &ui_img_png_battery4_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_charge = lv_img_create(ui_statusBar);
    lv_img_set_src(ui_charge, &ui_img_png_charge_png);
    lv_obj_set_width(ui_charge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_charge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_charge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_charge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_charge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_charge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_charge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_add_flag(ui_charge, LV_OBJ_FLAG_HIDDEN);     /// Flags
}

void battery_ui_update(int voltage, bool battery_exist, bool charging)
{
    int value = 0;

    if (battery_exist) {
        value = voltage;
    }

    lv_bar_set_value(ui_batBar, value , LV_ANIM_OFF);

    if (charging && battery_exist) {
        lv_obj_set_style_img_recolor(ui_charge, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        lv_obj_set_style_img_recolor(ui_charge, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void aht20_update_ui(uint8_t temp, uint8_t humi)
{

	if (ui_tempLable != NULL)
		lv_label_set_text_fmt(ui_tempLable, "%d""\xc2\xb0""C", temp);

	if (ui_humiLabel != NULL)
		lv_label_set_text_fmt(ui_humiLabel, "%d", humi);
}

