// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_min = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_tempLable = NULL;
lv_obj_t * ui_humi = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_humiImage = NULL;
lv_obj_t * ui_humiLabel = NULL;
lv_obj_t * ui_statusBar = NULL;
lv_obj_t * ui_batBar = NULL;
lv_obj_t * ui_charge = NULL;
lv_obj_t * ui_dataLabel = NULL;
lv_obj_t * ui____initial_actions0 = NULL;

const lv_img_dsc_t * ui_imgset_battery[2] = {&ui_img_png_battery0_png, &ui_img_png_battery4_png};
const lv_img_dsc_t * ui_imgset_humidity[1] = {&ui_img_png_humidity24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    //#error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_mono_init(dispp, false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
