// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void battery_ui_update(int voltage, bool battery_exist, bool charging);
void aht20_update_ui(uint8_t temp, uint8_t humi);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_tempLable;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_humi;
extern lv_obj_t * ui_humiImage;
extern lv_obj_t * ui_humiLabel;
extern lv_obj_t * ui_statusBar;
extern lv_obj_t * ui_batBar;
extern lv_obj_t * ui_charge;
extern lv_obj_t * ui_dataLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_png_wifi_png);    // assets/png/wifi.png
LV_IMG_DECLARE(ui_img_png_humidity24_png);    // assets/png/humidity032.png
LV_IMG_DECLARE(ui_img_png_battery0_png);    // assets/png/battery0.png
LV_IMG_DECLARE(ui_img_png_battery4_png);    // assets/png/battery4.png
LV_IMG_DECLARE(ui_img_png_charge_png);    // assets/png/charge.png

LV_FONT_DECLARE(ui_font_misansmedi82);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
